import { invoke } from "@tauri-apps/api/core";
import type { Achievement, ActivityRecord, AgentInstallation, AgentKind, AgentUsageBreakdown, CatalogAsset, ChangeSet, CloseBehavior, ContextPreview, ExcludedWorkspace, GitIdentitySummary, HeatmapPoint, InsightsQuery, InsightsStatus, InsightsSummary, InsightsView, LocalePreference, Manifest, McpHubStatus, McpInstallation, McpInstallResult, McpMigrationCandidate, McpNetworkSettings, McpOAuthStart, McpRegistryEntry, McpRuntimeStatus, McpServerConfig, McpToolDescriptor, MemoryRecord, MemoryStatus, MemoryType, ModelUsageBreakdown, ObsidianIntegration, ObsidianWorkspaceLink, QuotaCollectorStatus, QuotaSnapshot, RefreshJobStatus, RefreshKind, RefreshReceipt, RemoteGatewayInput, RemoteGatewaySummary, RepositoryCommitBreakdown, RuntimeInfo, ScanRoot, ThemePreference, WorkspaceScan, WorkspaceSummary, WorkspaceUsageBreakdown } from "./types";

export const api = {
  scan: (project: string) => invoke<WorkspaceScan>("scan_workspace", { project }),
  manifest: async (project: string) => {
    const manifest = await invoke<Manifest>("prepare_manifest", { project });
    // Empty legacy connections are omitted from manifest serialization.
    // Keep the React model total at the IPC boundary without writing the field back to disk.
    return { ...manifest, connections: manifest.connections ?? [] };
  },
  plan: (project: string, manifest: Manifest, includeHome: boolean) => invoke<ChangeSet>("plan_changes", { project, manifest, includeHome }),
  apply: (changeSet: ChangeSet, approveHome: boolean) => invoke("apply_changes", { changeSet, approveHome }),
  context: (project: string, cwd: string, agent: AgentKind) => invoke<ContextPreview>("resolve_context", { project, cwd, agent }),
  memories: (project: string, status?: MemoryStatus) => invoke<MemoryRecord[]>("list_memories", { project, status }),
  searchMemories: (project: string, query: string, limit = 50) => invoke<MemoryRecord[]>("search_memories", { project, query, limit }),
  proposeMemory: (project: string, content: string, memoryType: MemoryType) => invoke<MemoryRecord>("propose_memory", { project, proposal: { project_id: "", memory_type: memoryType, content, source_agent: "agentkib-desktop" } }),
  reviewMemory: (id: string, status: MemoryStatus, editedContent?: string) => invoke<MemoryRecord>("review_memory", { id, status, editedContent }),
  runtime: () => invoke<RuntimeInfo>("runtime_info"),
  setCloseBehavior: (behavior?: CloseBehavior) => invoke<void>("set_close_behavior", { behavior: behavior ?? null }),
  setLocale: (preference: LocalePreference) => invoke<RuntimeInfo>("set_locale", { preference }),
  setThemePreference: (preference: ThemePreference) => invoke<RuntimeInfo>("set_theme_preference", { preference }),
  mcpHubStatus: () => invoke<McpHubStatus>("get_mcp_hub_status"),
  updateMcpNetwork: (settings: McpNetworkSettings) => invoke<McpHubStatus>("update_mcp_network_settings", { settings }),
  mcpServers: (project?: string) => invoke<McpServerConfig[]>("list_mcp_servers", { project }),
  mcpServer: (serverId: string, project?: string) => invoke<McpServerConfig | undefined>("get_mcp_server", { serverId, project }),
  saveMcpServer: (server: McpServerConfig, project?: string) => invoke<McpServerConfig>("save_mcp_server", { server, project }),
  saveMcpLocalValues: (serverId: string, env: Record<string, string>, headers: Record<string, string>, project?: string) => invoke<void>("save_mcp_local_values", { serverId, env, headers, project }),
  removeMcpServer: (serverId: string, project?: string) => invoke<void>("remove_mcp_server", { serverId, project }),
  probeMcpRuntime: (serverId: string, project?: string) => invoke<McpToolDescriptor[]>("probe_mcp_runtime", { serverId, project }),
  startMcpOAuth: (serverId: string, project?: string) => invoke<McpOAuthStart>("start_mcp_oauth", { serverId, project }),
  mcpRuntimes: () => invoke<McpRuntimeStatus[]>("list_mcp_runtimes"),
  restartMcpRuntime: (serverId: string, project?: string) => invoke<McpToolDescriptor[]>("restart_mcp_runtime", { serverId, project }),
  stopMcpRuntime: (serverId?: string) => invoke<void>("stop_mcp_runtime", { serverId }),
  searchMcpRegistry: (query: string) => invoke<McpRegistryEntry[]>("search_mcp_registry", { query }),
  refreshMcpRegistry: (query: string) => invoke<McpRegistryEntry[]>("refresh_mcp_registry", { query }),
  installMcp: (entry: McpRegistryEntry, project?: string) => invoke<McpInstallResult>("install_mcp", { entry, project, confirmed: true }),
  updateMcp: (installationId: string, entry: McpRegistryEntry, project?: string) => invoke<McpInstallResult>("update_mcp", { installationId, entry, project, confirmed: true }),
  mcpInstallations: () => invoke<McpInstallation[]>("list_mcp_installations"),
  uninstallMcp: (installationId: string) => invoke<void>("uninstall_mcp", { installationId, confirmed: true }),
  nativeMcpCandidates: (project?: string) => invoke<McpMigrationCandidate[]>("scan_native_mcp_candidates", { project }),
  planMcpMigration: (project: string, candidateIds: string[]) => invoke<ChangeSet>("plan_mcp_migration", { project, candidateIds }),
  requestRefresh: (kind: RefreshKind, force = false) => invoke<RefreshReceipt>("request_refresh", { kind, force }),
  refreshStatus: () => invoke<RefreshJobStatus[]>("get_refresh_status"),
  discoverWorkspaces: () => invoke<RefreshReceipt>("discover_workspaces"),
  workspaces: () => invoke<WorkspaceSummary[]>("list_workspaces"),
  workspace: (id: string) => invoke<WorkspaceSummary | undefined>("get_workspace", { id }),
  addWorkspace: (path: string) => invoke<WorkspaceSummary>("add_workspace", { path }),
  refreshWorkspace: (id: string) => invoke<WorkspaceSummary>("refresh_workspace", { id }),
  excludeWorkspace: (id: string) => invoke<void>("exclude_workspace", { id }),
  excludedWorkspaces: () => invoke<ExcludedWorkspace[]>("list_excluded_workspaces"),
  restoreExcludedWorkspace: (path: string) => invoke<void>("restore_excluded_workspace", { path }),
  obsidianIntegration: () => invoke<ObsidianIntegration>("get_obsidian_integration"),
  addObsidianVault: (path: string) => invoke<ObsidianIntegration>("add_obsidian_vault", { path }),
  linkWorkspaceToObsidian: (workspaceId: string, vaultPath: string, relativeTarget?: string) => invoke<ObsidianWorkspaceLink>("link_workspace_to_obsidian", { workspaceId, vaultPath, relativeTarget: relativeTarget?.trim() || null }),
  unlinkWorkspaceFromObsidian: (workspaceId: string) => invoke<void>("unlink_workspace_from_obsidian", { workspaceId }),
  openObsidian: () => invoke<void>("open_obsidian"),
  openWorkspaceInObsidian: (workspaceId: string) => invoke<void>("open_workspace_in_obsidian", { workspaceId }),
  remoteGateways: () => invoke<RemoteGatewaySummary[]>("list_remote_gateways"),
  saveRemoteGateway: (input: RemoteGatewayInput) => invoke<RemoteGatewaySummary>("save_remote_gateway", { input }),
  refreshRemoteGateway: (id: string) => invoke<RemoteGatewaySummary>("refresh_remote_gateway", { id }),
  removeRemoteGateway: (id: string) => invoke<void>("remove_remote_gateway", { id }),
  scanRoots: () => invoke<ScanRoot[]>("list_scan_roots"),
  addScanRoot: (path: string, maxDepth = 5) => invoke<ScanRoot>("add_scan_root", { path, maxDepth }),
  removeScanRoot: (id: string) => invoke<void>("remove_scan_root", { id }),
  agentInstallations: () => invoke<AgentInstallation[]>("list_agent_installations"),
  catalogAssets: (query = "", agent?: AgentKind, workspaceId?: string, limit = 500) => invoke<CatalogAsset[]>("search_catalog_assets", { query, agent, workspaceId, limit }),
  globalMemories: (status?: MemoryStatus) => invoke<MemoryRecord[]>("list_global_memories", { status }),
  activity: (limit = 200) => invoke<ActivityRecord[]>("list_activity", { limit }),
  refreshInsights: () => invoke<RefreshReceipt>("refresh_insights"),
  insightsView: (query: InsightsQuery = {}) => invoke<InsightsView>("get_insights_view", { query }),
  insightsSummary: (query: InsightsQuery = {}) => invoke<InsightsSummary>("get_insights_summary", { query }),
  insightsHeatmap: (query: InsightsQuery = {}) => invoke<HeatmapPoint[]>("get_insights_heatmap", { query }),
  agentUsageBreakdown: (query: InsightsQuery = {}) => invoke<AgentUsageBreakdown[]>("get_agent_usage_breakdown", { query }),
  modelUsageBreakdown: (query: InsightsQuery = {}) => invoke<ModelUsageBreakdown[]>("get_model_usage_breakdown", { query }),
  workspaceUsageBreakdown: (query: InsightsQuery = {}) => invoke<WorkspaceUsageBreakdown[]>("get_workspace_usage_breakdown", { query }),
  repositoryCommitBreakdown: (query: InsightsQuery = {}) => invoke<RepositoryCommitBreakdown[]>("get_repository_commit_breakdown", { query }),
  achievements: () => invoke<Achievement[]>("list_achievements"),
  insightsStatus: () => invoke<InsightsStatus>("get_insights_status"),
  gitIdentities: () => invoke<GitIdentitySummary[]>("list_git_identities"),
  addGitIdentityAlias: (email: string) => invoke<GitIdentitySummary>("add_git_identity_alias", { email }),
  setGitIdentityEnabled: (id: string, enabled: boolean) => invoke<void>("set_git_identity_enabled", { id, enabled }),
  quotaSnapshot: () => invoke<QuotaSnapshot | undefined>("get_quota_snapshot"),
  refreshQuota: () => invoke<RefreshReceipt>("refresh_quota"),
  quotaCollectorStatus: () => invoke<QuotaCollectorStatus>("get_quota_collector_status"),
};
